// lib/products.js
export const PRODUCTS = [
    {
        id: "product-01",
        img: "/media/products/intro_01.jpg",
        name: "Birthday 1",
        subtitle: "On This Day A Queen Was Born.",
        price: 800,
        gallery: [
            "/media/products/intro_01.jpg",
            "/media/gallery/product1/1.jpg",
            "/media/gallery/product1/2.jpg",
            "/media/gallery/product1/3.jpg",
        ],
    },
    {
        id: "product-02",
        img: "/media/products/intro_02.jpg",
        name: "Congrats 1",
        subtitle: "Cheers To You.",
        price: 820,
        gallery: [
            "/media/products/intro_02.jpg",
            "/media/gallery/product2/2.jpg",
            "/media/gallery/product2/1.jpg",
            "/media/gallery/product2/3.jpg",
        ],
    },
    {
        id: "product-03",
        img: "/media/products/intro_03.jpg",
        name: "Birthday 2",
        subtitle: "More Fabulous Every Year.",
        price: 830,
        gallery: [
            "/media/products/intro_03.jpg",
            "/media/gallery/product3/2.jpg",
            "/media/gallery/product3/1.jpg",
            "/media/gallery/product3/4.jpg",
        ],
    },
    {
        id: "product-04",
        img: "/media/products/intro_04.jpg",
        name: "Birthday 3",
        subtitle: "Iconic, Always.",
        price: 840,
        gallery: [
            "/media/products/intro_04.jpg",
            "/media/gallery/product4/2.jpg",
            "/media/gallery/product4/3.jpg",
            "/media/gallery/product4/1.jpg",
            "/media/gallery/product4/4.jpg",
        ],
    },
    {
        id: "product-05",
        img: "/media/products/intro_05.jpg",
        name: "Congrats 2",
        subtitle: "Keep Shining.",
        price: 850,
        gallery: [
            "/media/products/intro_05.jpg",
            "/media/gallery/product5/1.jpg",
            "/media/gallery/product5/2.jpg",
            "/media/gallery/product5/3.jpg",
        ],
    },
    {
        id: "product-06",
        img: "/media/products/intro_06.jpg",
        name: "Generic 1",
        subtitle: "Thank You.",
        price: 860,
        gallery: [
            "/media/products/intro_06.jpg",
            "/media/gallery/product6/2.jpg",
            "/media/gallery/product6/3.jpg",
            "/media/gallery/product6/1.jpg",
            "/media/gallery/product6/4.jpg",
            "/media/gallery/product6/5.jpg",
        ],
    },
    {
        id: "product-07",
        img: "/media/products/intro_07.jpg",
        name: "Generic 2",
        subtitle: "Mon Chérie.",
        price: 870,
        gallery: [
            "/media/products/intro_07.jpg",
            "/media/gallery/product7/2.jpg",
            "/media/gallery/product7/3.jpg",
        ],
    },
    {
        id: "product-08",
        img: "/media/products/intro_08.jpg",
        name: "Generic 3",
        subtitle: "Checkmated For Life.",
        price: 880,
        gallery: [
            "/media/products/intro_08.jpg",
            "/media/gallery/product8/2.jpg",
            "/media/gallery/product8/3.jpg",
            "/media/gallery/product8/1.jpg",
        ],
    },
    {
        id: "product-09",
        img: "/media/products/intro_09.jpg",
        name: "Congrats 3",
        subtitle: "Celebrate The Wins.",
        price: 890,
        gallery: [
            "/media/products/intro_09.jpg",
            "/media/gallery/product9/2.jpg",
            "/media/gallery/product9/3.jpg",
            "/media/gallery/product9/1.jpg",
        ],
    },
    {
        id: "product-10",
        img: "/media/products/intro_10.jpg",
        name: "Birthday 4",
        subtitle: "More Fabulous Every Year.",
        price: 900,
        gallery: [
            "/media/products/intro_10.jpg",
            "/media/gallery/product10/2.jpg",
            "/media/gallery/product10/3.jpg",
            "/media/gallery/product10/1.jpg",
        ],
    },
    {
        id: "product-11",
        img: "/media/products/intro_11.jpg",
        name: "Generic 4",
        subtitle: "Sending You Love.",
        price: 910,
        gallery: [
            "/media/products/intro_11.jpg",
            "/media/gallery/product11/2.jpg",
            "/media/gallery/product11/3.jpg",
            "/media/gallery/product11/1.jpg",
        ],
    },
    {
        id: "product-12",
        img: "/media/products/intro_12.jpg",
        name: "Generic 5",
        subtitle: "My Mother.",
        price: 920,
        gallery: [
            "/media/products/intro_12.jpg",
            "/media/gallery/product12/2.jpg",
            "/media/gallery/product12/3.jpg",
            "/media/gallery/product12/1.jpg",
        ],
    },
    {
        id: "product-13",
        img: "/media/products/intro_13.jpg",
        name: "Generic 6",
        subtitle: "Un Fuerte Abrazo.",
        price: 930,
        gallery: [
            "/media/products/intro_13.jpg",
            "/media/gallery/product13/2.jpg",
            "/media/gallery/product13/3.jpg",
        ],
    },
    {
        id: "product-14",
        img: "/media/products/intro_14.jpg",
        name: "Generic 7",
        subtitle: "Olive You.",
        price: 940,
        gallery: [
            "/media/products/intro_14.jpg",
            "/media/gallery/product14/2.jpg",
            "/media/gallery/product14/3.jpg",
            "/media/gallery/product14/1.jpg",
        ],
    },
    {
        id: "product-15",
        img: "/media/products/intro_15.jpg",
        name: "Generic 8",
        subtitle: "Get Well Soon.",
        price: 950,
        gallery: [
            "/media/products/intro_15.jpg",
            "/media/gallery/product15/2.jpg",
            "/media/gallery/product15/3.jpg",
        ],
    },
    {
        id: "product-16",
        img: "/media/products/intro_16.jpg",
        name: "Generic 9",
        subtitle: "Je T’Aime.",
        price: 960,
        gallery: [
            "/media/products/intro_16.jpg",
            "/media/gallery/product16/2.jpg",
            "/media/gallery/product16/3.jpg",
            "/media/gallery/product16/1.jpg",
        ],
    },
];

export const PRODUCTS_VALENTIN = [
    {
        id: "product-valentin-01",
        img: "/media/products/intro_valentin_01.jpg",
        name: "Valentine’s Special 1",
        subtitle: "San Valentín 2026",
        price: 800,
        gallery: [
            "/media/products/intro_01.jpg",
            "/media/gallery/product1/1.jpg",
            "/media/gallery/product1/2.jpg",
            "/media/gallery/product1/3.jpg",
        ],
    },
    {
        id: "product-valentin-02",
        img: "/media/products/intro_valentin_02.jpg",
        name: "Valentine’s Special 2",
        subtitle: "San Valentín 2026",
        price: 800,
        gallery: [
            "/media/products/intro_01.jpg",
            "/media/gallery/product1/1.jpg",
            "/media/gallery/product1/2.jpg",
            "/media/gallery/product1/3.jpg",
        ],
    },
    {
        id: "product-07",
        img: "/media/products/intro_07.jpg",
        name: "Generic 2",
        subtitle: "Mon Chérie.",
        price: 870,
        gallery: [
            "/media/products/intro_07.jpg",
            "/media/gallery/product7/2.jpg",
            "/media/gallery/product7/3.jpg",
        ],
    },
    {
        id: "product-08",
        img: "/media/products/intro_08.jpg",
        name: "Generic 3",
        subtitle: "Checkmated For Life.",
        price: 880,
        gallery: [
            "/media/products/intro_08.jpg",
            "/media/gallery/product8/2.jpg",
            "/media/gallery/product8/3.jpg",
            "/media/gallery/product8/1.jpg",
        ],
    },
    {
        id: "product-11",
        img: "/media/products/intro_11.jpg",
        name: "Generic 4",
        subtitle: "Sending You Love.",
        price: 910,
        gallery: [
            "/media/products/intro_11.jpg",
            "/media/gallery/product11/2.jpg",
            "/media/gallery/product11/3.jpg",
            "/media/gallery/product11/1.jpg",
        ],
    },
    {
        id: "product-14",
        img: "/media/products/intro_14.jpg",
        name: "Generic 7",
        subtitle: "Olive You.",
        price: 940,
        gallery: [
            "/media/products/intro_14.jpg",
            "/media/gallery/product14/2.jpg",
            "/media/gallery/product14/3.jpg",
            "/media/gallery/product14/1.jpg",
        ],
    },
    {
        id: "product-16",
        img: "/media/products/intro_16.jpg",
        name: "Generic 9",
        subtitle: "Je T’Aime.",
        price: 960,
        gallery: [
            "/media/products/intro_16.jpg",
            "/media/gallery/product16/2.jpg",
            "/media/gallery/product16/3.jpg",
            "/media/gallery/product16/1.jpg",
        ],
    },
];

export const PRODUCTS_ALL = [
    {
        id: "product-01",
        img: "/media/products/intro_01.jpg",
        name: "Birthday 1",
        subtitle: "On This Day A Queen Was Born.",
        price: 800,
        gallery: [
            "/media/products/intro_01.jpg",
            "/media/gallery/product1/1.jpg",
            "/media/gallery/product1/2.jpg",
            "/media/gallery/product1/3.jpg",
        ],
    },
    {
        id: "product-02",
        img: "/media/products/intro_02.jpg",
        name: "Congrats 1",
        subtitle: "Cheers To You.",
        price: 820,
        gallery: [
            "/media/products/intro_02.jpg",
            "/media/gallery/product2/2.jpg",
            "/media/gallery/product2/1.jpg",
            "/media/gallery/product2/3.jpg",
        ],
    },
    {
        id: "product-03",
        img: "/media/products/intro_03.jpg",
        name: "Birthday 2",
        subtitle: "More Fabulous Every Year.",
        price: 830,
        gallery: [
            "/media/products/intro_03.jpg",
            "/media/gallery/product3/2.jpg",
            "/media/gallery/product3/1.jpg",
            "/media/gallery/product3/4.jpg",
        ],
    },
    {
        id: "product-04",
        img: "/media/products/intro_04.jpg",
        name: "Birthday 3",
        subtitle: "Iconic, Always.",
        price: 840,
        gallery: [
            "/media/products/intro_04.jpg",
            "/media/gallery/product4/2.jpg",
            "/media/gallery/product4/3.jpg",
            "/media/gallery/product4/1.jpg",
            "/media/gallery/product4/4.jpg",
        ],
    },
    {
        id: "product-05",
        img: "/media/products/intro_05.jpg",
        name: "Congrats 2",
        subtitle: "Keep Shining.",
        price: 850,
        gallery: [
            "/media/products/intro_05.jpg",
            "/media/gallery/product5/1.jpg",
            "/media/gallery/product5/2.jpg",
            "/media/gallery/product5/3.jpg",
        ],
    },
    {
        id: "product-06",
        img: "/media/products/intro_06.jpg",
        name: "Generic 1",
        subtitle: "Thank You.",
        price: 860,
        gallery: [
            "/media/products/intro_06.jpg",
            "/media/gallery/product6/2.jpg",
            "/media/gallery/product6/3.jpg",
            "/media/gallery/product6/1.jpg",
            "/media/gallery/product6/4.jpg",
            "/media/gallery/product6/5.jpg",
        ],
    },
    {
        id: "product-07",
        img: "/media/products/intro_07.jpg",
        name: "Generic 2",
        subtitle: "Mon Chérie.",
        price: 870,
        gallery: [
            "/media/products/intro_07.jpg",
            "/media/gallery/product7/2.jpg",
            "/media/gallery/product7/3.jpg",
        ],
    },
    {
        id: "product-08",
        img: "/media/products/intro_08.jpg",
        name: "Generic 3",
        subtitle: "Checkmated For Life.",
        price: 880,
        gallery: [
            "/media/products/intro_08.jpg",
            "/media/gallery/product8/2.jpg",
            "/media/gallery/product8/3.jpg",
            "/media/gallery/product8/1.jpg",
        ],
    },
    {
        id: "product-09",
        img: "/media/products/intro_09.jpg",
        name: "Congrats 3",
        subtitle: "Celebrate The Wins.",
        price: 890,
        gallery: [
            "/media/products/intro_09.jpg",
            "/media/gallery/product9/2.jpg",
            "/media/gallery/product9/3.jpg",
            "/media/gallery/product9/1.jpg",
        ],
    },
    {
        id: "product-10",
        img: "/media/products/intro_10.jpg",
        name: "Birthday 4",
        subtitle: "More Fabulous Every Year.",
        price: 900,
        gallery: [
            "/media/products/intro_10.jpg",
            "/media/gallery/product10/2.jpg",
            "/media/gallery/product10/3.jpg",
            "/media/gallery/product10/1.jpg",
        ],
    },
    {
        id: "product-11",
        img: "/media/products/intro_11.jpg",
        name: "Generic 4",
        subtitle: "Sending You Love.",
        price: 910,
        gallery: [
            "/media/products/intro_11.jpg",
            "/media/gallery/product11/2.jpg",
            "/media/gallery/product11/3.jpg",
            "/media/gallery/product11/1.jpg",
        ],
    },
    {
        id: "product-12",
        img: "/media/products/intro_12.jpg",
        name: "Generic 5",
        subtitle: "My Mother.",
        price: 920,
        gallery: [
            "/media/products/intro_12.jpg",
            "/media/gallery/product12/2.jpg",
            "/media/gallery/product12/3.jpg",
            "/media/gallery/product12/1.jpg",
        ],
    },
    {
        id: "product-13",
        img: "/media/products/intro_13.jpg",
        name: "Generic 6",
        subtitle: "Un Fuerte Abrazo.",
        price: 930,
        gallery: [
            "/media/products/intro_13.jpg",
            "/media/gallery/product13/2.jpg",
            "/media/gallery/product13/3.jpg",
        ],
    },
    {
        id: "product-14",
        img: "/media/products/intro_14.jpg",
        name: "Generic 7",
        subtitle: "Olive You.",
        price: 940,
        gallery: [
            "/media/products/intro_14.jpg",
            "/media/gallery/product14/2.jpg",
            "/media/gallery/product14/3.jpg",
            "/media/gallery/product14/1.jpg",
        ],
    },
    {
        id: "product-15",
        img: "/media/products/intro_15.jpg",
        name: "Generic 8",
        subtitle: "Get Well Soon.",
        price: 950,
        gallery: [
            "/media/products/intro_15.jpg",
            "/media/gallery/product15/2.jpg",
            "/media/gallery/product15/3.jpg",
        ],
    },
    {
        id: "product-16",
        img: "/media/products/intro_16.jpg",
        name: "Generic 9",
        subtitle: "Je T’Aime.",
        price: 960,
        gallery: [
            "/media/products/intro_16.jpg",
            "/media/gallery/product16/2.jpg",
            "/media/gallery/product16/3.jpg",
            "/media/gallery/product16/1.jpg",
        ],
    },
    {
        id: "product-valentin-01",
        img: "/media/products/intro_valentin_01.jpg",
        name: "Valentine’s Special 1",
        subtitle: "San Valentín 2026",
        price: 800,
        gallery: [
            "/media/products/intro_valentin_01.jpg",
            "/media/gallery/productv1/1.jpg",
            "/media/gallery/productv1/3.jpg",
        ],
    },
    {
        id: "product-valentin-02",
        img: "/media/products/intro_valentin_02.jpg",
        name: "Valentine’s Special 2",
        subtitle: "San Valentín 2026",
        price: 800,
        gallery: [
            "/media/products/intro_valentin_02.jpg",
            "/media/gallery/productv2/1.jpg",
            "/media/gallery/productv2/3.jpg",
        ],
    },
];

export function getProductById(id) {
    return PRODUCTS_ALL.find((p) => p.id === id);
}