// lib/products.js
export const PRODUCTS = [
    {
        id: "product-01",
        img: "/media/products/product-01.webp",
        name: "Birthday 1",
        subtitle: "On This Day A Queen Was Born.",
        price: 800,
        gallery: [
            "/media/gallery/product1/1.jpg",
            "/media/gallery/product1/2.jpg",
            "/media/gallery/product1/3.jpg",
            "/media/gallery/product1/4.jpg",
            "/media/gallery/product1/5.jpg",
        ],
    },
    {
        id: "product-02",
        img: "/media/products/product-02.webp",
        name: "Congrats 1",
        subtitle: "Cheers To You.",
        price: 820,
        gallery: [
            "/media/gallery/product2/1.jpg",
            "/media/gallery/product2/2.jpg",
            "/media/gallery/product2/3.jpg",
            "/media/gallery/product2/4.jpg",
        ],
    },
    {
        id: "product-03",
        img: "/media/products/product-03.webp",
        name: "Birthday 2",
        subtitle: "More Fabulous Every Year.",
        price: 830,
        gallery: [
            "/media/gallery/product3/1.jpg",
            "/media/gallery/product3/2.jpg",
            "/media/gallery/product3/3.jpg",
            "/media/gallery/product3/4.jpg",
            "/media/gallery/product3/5.jpg",
        ],
    },
    {
        id: "product-04",
        img: "/media/products/product-04.webp",
        name: "Birthday 3",
        subtitle: "Iconic, Always.",
        price: 840,
        gallery: [
            "/media/gallery/product4/1.jpg",
            "/media/gallery/product4/2.jpg",
            "/media/gallery/product4/3.jpg",
            "/media/gallery/product4/4.jpg",
            "/media/gallery/product4/5.jpg",
        ],
    },
    {
        id: "product-05",
        img: "/media/products/product-05.webp",
        name: "Congrats 2",
        subtitle: "Keep Shining.",
        price: 850,
        gallery: [
            "/media/gallery/product5/1.jpg",
            "/media/gallery/product5/2.jpg",
        ],
    },
    {
        id: "product-06",
        img: "/media/products/product-06.webp",
        name: "Generic 1",
        subtitle: "Thank You.",
        price: 860,
        gallery: [
            "/media/gallery/product6/1.jpg",
            "/media/gallery/product6/2.jpg",
            "/media/gallery/product6/3.jpg",
            "/media/gallery/product6/4.jpg",
            "/media/gallery/product6/5.jpg",
        ],
    },
    {
        id: "product-07",
        img: "/media/products/product-07.webp",
        name: "Generic 2",
        subtitle: "Mon Chérie.",
        price: 870,
        gallery: [
            "/media/gallery/product7/1.jpg",
            "/media/gallery/product7/2.jpg",
            "/media/gallery/product7/3.jpg",
            "/media/gallery/product7/4.jpg",
            "/media/gallery/product7/5.jpg",
        ],
    },
    {
        id: "product-08",
        img: "/media/products/product-08.webp",
        name: "Generic 3",
        subtitle: "Checkmated For Life.",
        price: 880,
        gallery: [
            "/media/gallery/product8/1.jpg",
            "/media/gallery/product8/2.jpg",
            "/media/gallery/product8/3.jpg",
            "/media/gallery/product8/4.jpg",
            "/media/gallery/product8/5.jpg",
        ],
    },
    {
        id: "product-09",
        img: "/media/products/product-09.webp",
        name: "Congrats 3",
        subtitle: "Celebrate The Wins.",
        price: 890,
        gallery: [
            "/media/gallery/product9/1.jpg",
            "/media/gallery/product9/2.jpg",
            "/media/gallery/product9/3.jpg",
            "/media/gallery/product9/4.jpg",
            "/media/gallery/product9/5.jpg",
        ],
    },
    {
        id: "product-10",
        img: "/media/products/product-10.webp",
        name: "Birthday 4",
        subtitle: "More Fabulous Every Year.",
        price: 900,
        gallery: [
            "/media/gallery/product10/1.jpg",
            "/media/gallery/product10/2.jpg",
            "/media/gallery/product10/3.jpg",
            "/media/gallery/product10/4.jpg",
            "/media/gallery/product10/5.jpg",
        ],
    },
    {
        id: "product-11",
        img: "/media/products/product-11.webp",
        name: "Generic 4",
        subtitle: "Sending You Love.",
        price: 910,
        gallery: [
            "/media/gallery/product11/1.jpg",
            "/media/gallery/product11/2.jpg",
            "/media/gallery/product11/3.jpg",
            "/media/gallery/product11/4.jpg",
            "/media/gallery/product11/5.jpg",
        ],
    },
    {
        id: "product-12",
        img: "/media/products/product-12.webp",
        name: "Generic 5",
        subtitle: "My Mother.",
        price: 920,
        gallery: [
            "/media/gallery/product12/1.jpg",
            "/media/gallery/product12/2.jpg",
            "/media/gallery/product12/3.jpg",
            "/media/gallery/product12/4.jpg",
            "/media/gallery/product12/5.jpg",
        ],
    },
    {
        id: "product-13",
        img: "/media/products/product-13.webp",
        name: "Generic 6",
        subtitle: "Un Fuerte Abrazo.",
        price: 930,
        gallery: [
            "/media/gallery/product13/1.jpg",
            "/media/gallery/product13/2.jpg",
            "/media/gallery/product13/3.jpg",
        ],
    },
    {
        id: "product-14",
        img: "/media/products/product-14.webp",
        name: "Generic 7",
        subtitle: "Olive You.",
        price: 940,
        gallery: [
            "/media/gallery/product14/1.jpg",
            "/media/gallery/product14/2.jpg",
            "/media/gallery/product14/3.jpg",
            "/media/gallery/product14/4.jpg",
            "/media/gallery/product14/5.jpg",
        ],
    },
    {
        id: "product-15",
        img: "/media/products/product-15.webp",
        name: "Generic 8",
        subtitle: "Get Well Soon.",
        price: 950,
        gallery: [
            "/media/gallery/product15/1.jpg",
            "/media/gallery/product15/2.jpg",
            "/media/gallery/product15/3.jpg",
        ],
    },
    {
        id: "product-16",
        img: "/media/products/product-16.webp",
        name: "Generic 9",
        subtitle: "Je T’Aime.",
        price: 960,
        gallery: [
            "/media/gallery/product16/1.jpg",
            "/media/gallery/product16/2.jpg",
            "/media/gallery/product16/3.jpg",
            "/media/gallery/product16/4.jpg",
            "/media/gallery/product16/5.jpg",
        ],
    },
];

export function getProductById(id) {
    return PRODUCTS.find((p) => p.id === id);
}